<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.1" />
    <xacro:property name="base_width" value="0.1" />
    <xacro:property name="base_height" value="0.02" />
    <xacro:property name="cylinder_radius" value="0.02" />
    <xacro:property name="cylinder_length" value="0.3" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.5" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
    </link>                       
    
    <link name="forearm_link">
      <visual>
        <geometry>
          <cylinder radius="${cylinder_radius}" length="${cylinder_length}" />
        </geometry>
        <origin xyz="0 0 ${cylinder_length/2.0}" rpy="0 0 0" />
        <material name="yellow" />
      </visual>
      <collision>
         <geometry>
          <cylinder radius="${cylinder_radius}" length="${cylinder_length}" />
        </geometry>
        <origin xyz="0 0 ${cylinder_length/2.0}" rpy="0 0 0" />
      </collision>
      <xacro:cylinder_inertia m="0.3" r="${2*cylinder_radius}" h="${2*cylinder_length}" 
                                    xyz="0 0 ${cylinder_length/2.0}" rpy="0 0 0" />
    </link>     

    <link name="hand_link">
      <visual>
        <geometry>
          <cylinder radius="${cylinder_radius}" length="${cylinder_length}" />
        </geometry>
        <origin xyz="0 0 ${cylinder_length/2.0}" rpy="0 0 0" />
        <material name="orange" />
      </visual>
      <collision>
         <geometry>
          <cylinder radius="${cylinder_radius}" length="${cylinder_length}" />
        </geometry>
        <origin xyz="0 0 ${cylinder_length/2.0}" rpy="0 0 0" />
      </collision>
      <xacro:cylinder_inertia m="0.3" r="${2*cylinder_radius}" h="${2*cylinder_length}" 
                                    xyz="0 0 ${cylinder_length/2.0}" rpy="0 0 0" />
    </link>                                     
    
    <joint name="base_forearm" type="revolute">
      <parent link="arm_base_link"/>
      <child link="forearm_link"/>
      <origin xyz="0 0 0.015" rpy="0 0 0"/>
      <dynamics damping="0.1" friction="0.05" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="100" lower="0" upper="${pi/2.0}" />
      </joint>

    <joint name="forearm_hand" type="revolute">
      <parent link="forearm_link"/>
      <child link="hand_link"/>
      <origin xyz="0 0 0.3" rpy="0 0 0"/>
      <dynamics damping="0.1" friction="0.05" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="100" lower="0" upper="${pi/2.0}" />
      </joint>  

    <gazebo reference="arm_base_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="forearm_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <gazebo reference="hand_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo>
      <plugin name="gazebo_ros_joint_state_publisher"
          filename="libgazebo_ros_joint_state_publisher.so">
  
        <!-- Update rate in Hertz -->
        <update_rate>10</update_rate>
  
        <!-- Name of joints in the model whose states will be published. -->
        <joint_name>base_forearm</joint_name>
        <joint_name>forearm_hand</joint_name>
  
      </plugin> 
    </gazebo>

    <gazebo>
       <plugin name="gazebo_ros_joint_pose_trajectory"
           filename="libgazebo_ros_joint_pose_trajectory.so">
   
      
         <!-- Update rate in Hz -->
         <update_rate>2</update_rate>
   
       </plugin>
    </gazebo>

</robot>