controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel_names: ["base_left_wheel_joint"]
      right_wheel_names: ["base_right_wheel_joint"]
      cmd_vel_timeout: 0.5
      publish_rate: 50
      odom_frame_id: "odom"
      base_frame_id: "base_footprint"
      use_stamped_vel: false
      wheel_separation: 0.45
      wheel_radius: 0.1
      enable_odom_tf: true

